export enum ConfigEnum {
  DB = 'DB',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_PORT = 'DB_PORT',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
  DB_RETRY = 'DB_RETRY',
}
